---

- name: Apply configurations to local machine
  hosts: localhost

  pre_tasks:
    - name: Get the username of the user running ansible
      local_action: command whoami
      register: host_username
      become: False

    - set_fact:
        host_username: "{{host_username.stdout}}"
        home_directory: "/home/{{host_username.stdout}}"
        ssh_directory: "/home/{{host_username.stdout}}/.ssh"
        
    - name: Update apt repository cache
      apt:
        update_cache: True

  post_tasks:
    - name: Install missing dependencies
      shell: apt-get install -f -y
      ignore_errors: True

  roles:
    - common
    - development
    - aesthetics
    - social

  become: True
