- name: Add Oranchelo repisotry
  apt_repository:
    repo: "ppa:oranchelo/oranchelo-icon-theme"
    state: present

- name: Install Oranchelo icons
  apt:
    name: oranchelo-icon-theme
    state: present
