- name: Check Teamviewer installed
  shell: which teamviewer
  register: teamviewer_check
  ignore_errors: True

- name: Install Teamviewer
  shell: |
    wget -O tv.deb https://download.teamviewer.com/download/teamviewer_i386.deb
    dpkg --install tv.deb
    rm -rf tv.deb
  when: teamviewer_check.rc == 1

- name: Install Teams
  shell: snap install teams-for-linux
